import type {
  ApplicantRow,
  EvaluationProgress,
  EvaluationResult,
  StageEvaluation,
} from "./applicantListTypes"

export const APPLICANT_LIST_BASE_TIME_MOCK = "26-07-04 02:48"

export const RECRUITING_TARGET_GISU_LABEL_MOCK = "UMC 11기"

const evaluation = (
  progress: EvaluationProgress,
  doneCount: number,
  totalCount: number,
  result: EvaluationResult | null,
  myProgress: EvaluationProgress,
): StageEvaluation => ({ progress, doneCount, totalCount, result, myProgress })

export const APPLICANT_LIST_MOCK: ApplicantRow[] = [
  {
    applicationId: "101",
    appliedAt: "2026-04-22T03:33:00",
    interviewAt: "2026-05-02T14:00:00",
    applicantName: "이예원",
    chapter: "Chromium",
    school: "광운대",
    recruitmentType: "regular",
    parts: ["design"],
    evaluations: {
      document: evaluation("done", 7, 7, "pass", "done"),
      interview: evaluation("done", 7, 7, "pass", "done"),
      final: evaluation("inProgress", 2, 5, null, "inProgress"),
    },
  },
  {
    applicationId: "102",
    appliedAt: "2026-04-22T03:21:00",
    interviewAt: "2026-05-02T15:00:00",
    applicantName: "황지원",
    chapter: "Chromium",
    school: "서울여대",
    recruitmentType: "regular",
    parts: ["pm"],
    evaluations: {
      document: evaluation("done", 7, 7, "pass", "done"),
      interview: evaluation("done", 7, 7, "pass", "done"),
      final: evaluation("done", 5, 5, "pass", "done"),
    },
  },
  {
    applicationId: "103",
    appliedAt: "2026-04-22T02:58:00",
    interviewAt: null,
    applicantName: "강지훈",
    chapter: "Ferrum",
    school: "홍익대 서울",
    recruitmentType: "additional",
    additionalRound: 2,
    parts: ["mobile-pe", "web-pe"],
    evaluations: {
      document: evaluation("inProgress", 3, 7, null, "inProgress"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "104",
    appliedAt: "2026-04-22T02:44:00",
    interviewAt: "2026-05-03T10:00:00",
    applicantName: "한현서",
    chapter: "Ferrum",
    school: "이화여대",
    recruitmentType: "regular",
    parts: ["web-pe"],
    evaluations: {
      document: evaluation("done", 7, 7, "pass", "done"),
      interview: evaluation("done", 7, 7, "pass", "done"),
      final: evaluation("done", 5, 5, "pass", "done"),
    },
  },
  {
    applicationId: "105",
    appliedAt: "2026-04-22T02:31:00",
    interviewAt: null,
    applicantName: "양혜원",
    chapter: "Neon",
    school: "숙명여대",
    recruitmentType: "regular",
    parts: ["web-pe"],
    evaluations: {
      document: evaluation("inProgress", 4, 7, null, "done"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "106",
    appliedAt: "2026-04-22T02:10:00",
    interviewAt: "2026-05-03T11:00:00",
    applicantName: "오창준",
    chapter: "Neon",
    school: "인하대",
    recruitmentType: "regular",
    parts: ["web-pe", "mobile-pe"],
    evaluations: {
      document: evaluation("done", 7, 7, "pass", "done"),
      interview: evaluation("done", 7, 7, "pass", "done"),
      final: evaluation("done", 5, 5, "fail", "done"),
    },
  },
  {
    applicationId: "107",
    appliedAt: "2026-04-22T01:52:00",
    interviewAt: null,
    applicantName: "김도연",
    chapter: "Platinum",
    school: "동아대",
    recruitmentType: "regular",
    parts: ["mobile-pe", "web-pe"],
    evaluations: {
      document: evaluation("inProgress", 2, 7, null, "before"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "108",
    appliedAt: "2026-04-22T01:41:00",
    interviewAt: null,
    applicantName: "박성현",
    chapter: "Platinum",
    school: "영남대",
    recruitmentType: "additional",
    additionalRound: 2,
    parts: ["pm"],
    evaluations: {
      document: evaluation("before", 0, 7, null, "before"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "109",
    appliedAt: "2026-04-22T01:22:00",
    interviewAt: null,
    applicantName: "이지은",
    chapter: "Selenium",
    school: "성신여대",
    recruitmentType: "regular",
    parts: ["design"],
    evaluations: {
      document: evaluation("done", 7, 7, "fail", "done"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "110",
    appliedAt: "2026-04-22T01:05:00",
    interviewAt: null,
    applicantName: "정민준",
    chapter: "Selenium",
    school: "숭실대",
    recruitmentType: "regular",
    parts: ["web-pe"],
    evaluations: {
      document: evaluation("inProgress", 5, 7, null, "inProgress"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "111",
    appliedAt: "2026-04-22T00:48:00",
    interviewAt: "2026-05-04T13:00:00",
    applicantName: "최수아",
    chapter: "Xenon",
    school: "중앙대",
    recruitmentType: "regular",
    parts: ["design", "pm"],
    evaluations: {
      document: evaluation("done", 7, 7, "pass", "done"),
      interview: evaluation("before", 0, 7, null, "before"),
      final: null,
    },
  },
  {
    applicationId: "112",
    appliedAt: "2026-04-22T00:31:00",
    interviewAt: null,
    applicantName: "임서준",
    chapter: "Xenon",
    school: "한성대",
    recruitmentType: "additional",
    additionalRound: 3,
    parts: ["mobile-pe"],
    evaluations: {
      document: evaluation("before", 0, 7, null, "before"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "113",
    appliedAt: "2026-04-21T23:58:00",
    interviewAt: null,
    applicantName: "김하은",
    chapter: "Chromium",
    school: "한국외대",
    recruitmentType: "regular",
    parts: ["web-pe"],
    evaluations: {
      document: evaluation("inProgress", 3, 7, null, "done"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "114",
    appliedAt: "2026-04-21T23:40:00",
    interviewAt: null,
    applicantName: "박지호",
    chapter: "Ferrum",
    school: "동국대",
    recruitmentType: "regular",
    parts: ["pm"],
    evaluations: {
      document: evaluation("done", 7, 7, "fail", "done"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "115",
    appliedAt: "2026-04-21T23:12:00",
    interviewAt: null,
    applicantName: "윤서연",
    chapter: "Neon",
    school: "가천대",
    recruitmentType: "regular",
    parts: ["design"],
    evaluations: {
      document: evaluation("inProgress", 6, 7, null, "inProgress"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "116",
    appliedAt: "2026-04-21T22:55:00",
    interviewAt: "2026-05-04T16:00:00",
    applicantName: "장예준",
    chapter: "Platinum",
    school: "인제대",
    recruitmentType: "regular",
    parts: ["mobile-pe"],
    evaluations: {
      document: evaluation("done", 7, 7, "pass", "done"),
      interview: evaluation("done", 7, 7, "fail", "done"),
      final: null,
    },
  },
  {
    applicationId: "117",
    appliedAt: "2026-04-21T22:34:00",
    interviewAt: null,
    applicantName: "서지우",
    chapter: "Selenium",
    school: "한양대 ERICA",
    recruitmentType: "additional",
    additionalRound: 2,
    parts: ["web-pe", "mobile-pe"],
    evaluations: {
      document: evaluation("inProgress", 1, 7, null, "before"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "118",
    appliedAt: "2026-04-21T22:03:00",
    interviewAt: "2026-05-05T10:30:00",
    applicantName: "문채원",
    chapter: "Xenon",
    school: "가톨릭대",
    recruitmentType: "regular",
    parts: ["pm"],
    evaluations: {
      document: evaluation("done", 7, 7, "pass", "done"),
      interview: evaluation("done", 7, 7, "pass", "done"),
      final: evaluation("before", 0, 5, null, "before"),
    },
  },
  {
    applicationId: "119",
    appliedAt: "2026-04-21T21:47:00",
    interviewAt: null,
    applicantName: "신동현",
    chapter: "Chromium",
    school: "동양미래대",
    recruitmentType: "regular",
    parts: ["web-pe"],
    evaluations: {
      document: evaluation("before", 0, 7, null, "before"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "120",
    appliedAt: "2026-04-21T21:30:00",
    interviewAt: "2026-05-05T14:00:00",
    applicantName: "홍유진",
    chapter: "Ferrum",
    school: "홍익대 세종",
    recruitmentType: "regular",
    parts: ["design"],
    evaluations: {
      document: evaluation("done", 7, 7, "pass", "done"),
      interview: evaluation("inProgress", 2, 7, null, "inProgress"),
      final: null,
    },
  },
  {
    applicationId: "121",
    appliedAt: "2026-04-21T21:11:00",
    interviewAt: null,
    applicantName: "권민재",
    chapter: "Neon",
    school: "동덕여대",
    recruitmentType: "additional",
    additionalRound: 2,
    parts: ["mobile-pe"],
    evaluations: {
      document: evaluation("inProgress", 3, 7, null, "inProgress"),
      interview: null,
      final: null,
    },
  },
]
