import type { Chapter } from "@/entities/organization/model/chapters"

import type {
  ApplicantRow,
  EvaluationProgress,
  EvaluationResult,
  StageEvaluation,
} from "./applicantListTypes"

export const APPLICANT_LIST_BASE_TIME_MOCK = "26-07-04 02:48"

export const RECRUITING_TARGET_GISU_LABEL_MOCK = "UMC 11기"

export const RECRUITING_MY_CHAPTER_MOCK: Chapter = "Ferrum"

export const RECRUITING_MY_SCHOOL_MOCK = "이화여대"

const evaluation = (
  progress: EvaluationProgress,
  result: EvaluationResult | null,
  myProgress: EvaluationProgress,
): StageEvaluation => ({ progress, result, myProgress })

export const APPLICANT_LIST_MOCK: ApplicantRow[] = [
  {
    applicationId: "101",
    roundId: "9001",
    appliedAt: "2026-04-22T03:33:00",
    applicantName: "이예원",
    chapter: "Chromium",
    school: "광운대",
    recruitmentType: "regular",
    parts: ["design"],
    evaluations: {
      document: evaluation("done", "pass", "done"),
      interview: evaluation("done", "pass", "done"),
      final: evaluation("inProgress", null, "inProgress"),
    },
  },
  {
    applicationId: "102",
    roundId: "9001",
    appliedAt: "2026-04-22T03:21:00",
    applicantName: "황지원",
    chapter: "Chromium",
    school: "서울여대",
    recruitmentType: "regular",
    parts: ["pm"],
    evaluations: {
      document: evaluation("done", "pass", "done"),
      interview: evaluation("done", "pass", "done"),
      final: evaluation("done", "pass", "done"),
    },
  },
  {
    applicationId: "103",
    roundId: "9001",
    appliedAt: "2026-04-22T02:58:00",
    applicantName: "강지훈",
    chapter: "Ferrum",
    school: "홍익대 서울",
    recruitmentType: "additional",
    additionalRound: 2,
    parts: ["mobile-pe", "web-pe"],
    evaluations: {
      document: evaluation("inProgress", null, "inProgress"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "104",
    roundId: "9001",
    appliedAt: "2026-04-22T02:44:00",
    applicantName: "한현서",
    chapter: "Ferrum",
    school: "이화여대",
    recruitmentType: "regular",
    parts: ["web-pe"],
    evaluations: {
      document: {
        ...evaluation("done", "pass", "done"),
      },
      interview: evaluation("done", "pass", "done"),
      final: evaluation("done", "pass", "done"),
    },
  },
  {
    applicationId: "105",
    roundId: "9001",
    appliedAt: "2026-04-22T02:31:00",
    applicantName: "양혜원",
    chapter: "Neon",
    school: "숙명여대",
    recruitmentType: "regular",
    parts: ["web-pe"],
    evaluations: {
      document: evaluation("inProgress", null, "done"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "106",
    roundId: "9001",
    appliedAt: "2026-04-22T02:10:00",
    applicantName: "오창준",
    chapter: "Neon",
    school: "인하대",
    recruitmentType: "regular",
    parts: ["web-pe", "mobile-pe"],
    evaluations: {
      document: evaluation("done", "pass", "done"),
      interview: evaluation("done", "pass", "done"),
      final: evaluation("done", "fail", "done"),
    },
  },
  {
    applicationId: "107",
    roundId: "9001",
    appliedAt: "2026-04-22T01:52:00",
    applicantName: "김도연",
    chapter: "Platinum",
    school: "동아대",
    recruitmentType: "regular",
    parts: ["mobile-pe", "web-pe"],
    evaluations: {
      document: evaluation("inProgress", null, "before"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "108",
    roundId: "9001",
    appliedAt: "2026-04-22T01:41:00",
    applicantName: "박성현",
    chapter: "Platinum",
    school: "영남대",
    recruitmentType: "additional",
    additionalRound: 2,
    parts: ["pm"],
    evaluations: {
      document: evaluation("before", null, "before"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "109",
    roundId: "9001",
    appliedAt: "2026-04-22T01:22:00",
    applicantName: "이지은",
    chapter: "Selenium",
    school: "성신여대",
    recruitmentType: "regular",
    parts: ["design"],
    evaluations: {
      document: evaluation("done", "fail", "done"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "110",
    roundId: "9001",
    appliedAt: "2026-04-22T01:05:00",
    applicantName: "정민준",
    chapter: "Selenium",
    school: "숭실대",
    recruitmentType: "regular",
    parts: ["web-pe"],
    evaluations: {
      document: evaluation("inProgress", null, "inProgress"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "111",
    roundId: "9001",
    appliedAt: "2026-04-22T00:48:00",
    applicantName: "최수아",
    chapter: "Xenon",
    school: "중앙대",
    recruitmentType: "regular",
    parts: ["design", "pm"],
    evaluations: {
      document: evaluation("done", "pass", "done"),
      interview: evaluation("before", null, "before"),
      final: null,
    },
  },
  {
    applicationId: "112",
    roundId: "9001",
    appliedAt: "2026-04-22T00:31:00",
    applicantName: "임서준",
    chapter: "Xenon",
    school: "한성대",
    recruitmentType: "additional",
    additionalRound: 3,
    parts: ["mobile-pe"],
    evaluations: {
      document: evaluation("before", null, "before"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "113",
    roundId: "9001",
    appliedAt: "2026-04-21T23:58:00",
    applicantName: "김하은",
    chapter: "Chromium",
    school: "한국외대",
    recruitmentType: "regular",
    parts: ["web-pe"],
    evaluations: {
      document: evaluation("inProgress", null, "done"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "114",
    roundId: "9001",
    appliedAt: "2026-04-21T23:40:00",
    applicantName: "박지호",
    chapter: "Ferrum",
    school: "동국대",
    recruitmentType: "regular",
    parts: ["pm"],
    evaluations: {
      document: evaluation("done", "fail", "done"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "115",
    roundId: "9001",
    appliedAt: "2026-04-21T23:12:00",
    applicantName: "윤서연",
    chapter: "Neon",
    school: "가천대",
    recruitmentType: "regular",
    parts: ["design"],
    evaluations: {
      document: evaluation("inProgress", null, "inProgress"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "116",
    roundId: "9001",
    appliedAt: "2026-04-21T22:55:00",
    applicantName: "장예준",
    chapter: "Platinum",
    school: "인제대",
    recruitmentType: "regular",
    parts: ["mobile-pe"],
    evaluations: {
      document: evaluation("done", "pass", "done"),
      interview: evaluation("done", "fail", "done"),
      final: null,
    },
  },
  {
    applicationId: "117",
    roundId: "9001",
    appliedAt: "2026-04-21T22:34:00",
    applicantName: "서지우",
    chapter: "Selenium",
    school: "한양대 ERICA",
    recruitmentType: "additional",
    additionalRound: 2,
    parts: ["web-pe", "mobile-pe"],
    evaluations: {
      document: evaluation("inProgress", null, "before"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "118",
    roundId: "9001",
    appliedAt: "2026-04-21T22:03:00",
    applicantName: "문채원",
    chapter: "Xenon",
    school: "가톨릭대",
    recruitmentType: "regular",
    parts: ["pm"],
    evaluations: {
      document: evaluation("done", "pass", "done"),
      interview: evaluation("done", "pass", "done"),
      final: evaluation("before", null, "before"),
    },
  },
  {
    applicationId: "119",
    roundId: "9001",
    appliedAt: "2026-04-21T21:47:00",
    applicantName: "신동현",
    chapter: "Chromium",
    school: "동양미래대",
    recruitmentType: "regular",
    parts: ["web-pe"],
    evaluations: {
      document: evaluation("before", null, "before"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "120",
    roundId: "9001",
    appliedAt: "2026-04-21T21:30:00",
    applicantName: "홍유진",
    chapter: "Ferrum",
    school: "홍익대 세종",
    recruitmentType: "regular",
    parts: ["design"],
    evaluations: {
      document: evaluation("done", "pass", "done"),
      interview: evaluation("inProgress", null, "inProgress"),
      final: null,
    },
  },
  {
    applicationId: "121",
    roundId: "9001",
    appliedAt: "2026-04-21T21:11:00",
    applicantName: "권민재",
    chapter: "Neon",
    school: "동덕여대",
    recruitmentType: "additional",
    additionalRound: 2,
    parts: ["mobile-pe"],
    evaluations: {
      document: evaluation("inProgress", null, "inProgress"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "122",
    roundId: "9001",
    appliedAt: "2026-04-21T20:42:00",
    applicantName: "조은별",
    chapter: "Ferrum",
    school: "이화여대",
    recruitmentType: "regular",
    parts: ["design"],
    evaluations: {
      document: evaluation("inProgress", null, "before"),
      interview: null,
      final: null,
    },
  },
  {
    applicationId: "123",
    roundId: "9001",
    appliedAt: "2026-04-21T20:15:00",
    applicantName: "남지호",
    chapter: "Ferrum",
    school: "이화여대",
    recruitmentType: "additional",
    additionalRound: 2,
    parts: ["pm", "design"],
    evaluations: {
      document: {
        ...evaluation("done", null, "done"),
      },
      interview: null,
      final: null,
    },
  },
]
