/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MatchingRouteRouteImport } from './routes/matching/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchingIndexRouteImport } from './routes/matching/index'
import { Route as TestTooltipRouteImport } from './routes/test/tooltip'
import { Route as TestToastRouteImport } from './routes/test/toast'
import { Route as TestOptionButtonRouteImport } from './routes/test/option-button'
import { Route as TestMemberSearchBarRouteImport } from './routes/test/member-search-bar'
import { Route as TestCounterRouteImport } from './routes/test/counter'
import { Route as TestChipRouteImport } from './routes/test/chip'
import { Route as TestButtonRouteImport } from './routes/test/button'
import { Route as MatchingRoundsRouteImport } from './routes/matching/rounds'
import { Route as MatchingApplicationsRouteImport } from './routes/matching/applications'
import { Route as MatchingProjectsIndexRouteImport } from './routes/matching/projects/index'
import { Route as MatchingProjectsNewRouteImport } from './routes/matching/projects/new'
import { Route as MatchingProjectsAnnounceRouteImport } from './routes/matching/projects/announce'

const MatchingRouteRoute = MatchingRouteRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingIndexRoute = MatchingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const TestTooltipRoute = TestTooltipRouteImport.update({
  id: '/test/tooltip',
  path: '/test/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const TestToastRoute = TestToastRouteImport.update({
  id: '/test/toast',
  path: '/test/toast',
  getParentRoute: () => rootRouteImport,
} as any)
const TestOptionButtonRoute = TestOptionButtonRouteImport.update({
  id: '/test/option-button',
  path: '/test/option-button',
  getParentRoute: () => rootRouteImport,
} as any)
const TestMemberSearchBarRoute = TestMemberSearchBarRouteImport.update({
  id: '/test/member-search-bar',
  path: '/test/member-search-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCounterRoute = TestCounterRouteImport.update({
  id: '/test/counter',
  path: '/test/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const TestChipRoute = TestChipRouteImport.update({
  id: '/test/chip',
  path: '/test/chip',
  getParentRoute: () => rootRouteImport,
} as any)
const TestButtonRoute = TestButtonRouteImport.update({
  id: '/test/button',
  path: '/test/button',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoundsRoute = MatchingRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const MatchingApplicationsRoute = MatchingApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const MatchingProjectsIndexRoute = MatchingProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const MatchingProjectsNewRoute = MatchingProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const MatchingProjectsAnnounceRoute =
  MatchingProjectsAnnounceRouteImport.update({
    id: '/projects/announce',
    path: '/projects/announce',
    getParentRoute: () => MatchingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/matching': typeof MatchingRouteRouteWithChildren
  '/matching/applications': typeof MatchingApplicationsRoute
  '/matching/rounds': typeof MatchingRoundsRoute
  '/test/button': typeof TestButtonRoute
  '/test/chip': typeof TestChipRoute
  '/test/counter': typeof TestCounterRoute
  '/test/member-search-bar': typeof TestMemberSearchBarRoute
  '/test/option-button': typeof TestOptionButtonRoute
  '/test/toast': typeof TestToastRoute
  '/test/tooltip': typeof TestTooltipRoute
  '/matching/': typeof MatchingIndexRoute
  '/matching/projects/announce': typeof MatchingProjectsAnnounceRoute
  '/matching/projects/new': typeof MatchingProjectsNewRoute
  '/matching/projects/': typeof MatchingProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/matching/applications': typeof MatchingApplicationsRoute
  '/matching/rounds': typeof MatchingRoundsRoute
  '/test/button': typeof TestButtonRoute
  '/test/chip': typeof TestChipRoute
  '/test/counter': typeof TestCounterRoute
  '/test/member-search-bar': typeof TestMemberSearchBarRoute
  '/test/option-button': typeof TestOptionButtonRoute
  '/test/toast': typeof TestToastRoute
  '/test/tooltip': typeof TestTooltipRoute
  '/matching': typeof MatchingIndexRoute
  '/matching/projects/announce': typeof MatchingProjectsAnnounceRoute
  '/matching/projects/new': typeof MatchingProjectsNewRoute
  '/matching/projects': typeof MatchingProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/matching': typeof MatchingRouteRouteWithChildren
  '/matching/applications': typeof MatchingApplicationsRoute
  '/matching/rounds': typeof MatchingRoundsRoute
  '/test/button': typeof TestButtonRoute
  '/test/chip': typeof TestChipRoute
  '/test/counter': typeof TestCounterRoute
  '/test/member-search-bar': typeof TestMemberSearchBarRoute
  '/test/option-button': typeof TestOptionButtonRoute
  '/test/toast': typeof TestToastRoute
  '/test/tooltip': typeof TestTooltipRoute
  '/matching/': typeof MatchingIndexRoute
  '/matching/projects/announce': typeof MatchingProjectsAnnounceRoute
  '/matching/projects/new': typeof MatchingProjectsNewRoute
  '/matching/projects/': typeof MatchingProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/matching'
    | '/matching/applications'
    | '/matching/rounds'
    | '/test/button'
    | '/test/chip'
    | '/test/counter'
    | '/test/member-search-bar'
    | '/test/option-button'
    | '/test/toast'
    | '/test/tooltip'
    | '/matching/'
    | '/matching/projects/announce'
    | '/matching/projects/new'
    | '/matching/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/matching/applications'
    | '/matching/rounds'
    | '/test/button'
    | '/test/chip'
    | '/test/counter'
    | '/test/member-search-bar'
    | '/test/option-button'
    | '/test/toast'
    | '/test/tooltip'
    | '/matching'
    | '/matching/projects/announce'
    | '/matching/projects/new'
    | '/matching/projects'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/matching'
    | '/matching/applications'
    | '/matching/rounds'
    | '/test/button'
    | '/test/chip'
    | '/test/counter'
    | '/test/member-search-bar'
    | '/test/option-button'
    | '/test/toast'
    | '/test/tooltip'
    | '/matching/'
    | '/matching/projects/announce'
    | '/matching/projects/new'
    | '/matching/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRoute
  MatchingRouteRoute: typeof MatchingRouteRouteWithChildren
  TestButtonRoute: typeof TestButtonRoute
  TestChipRoute: typeof TestChipRoute
  TestCounterRoute: typeof TestCounterRoute
  TestMemberSearchBarRoute: typeof TestMemberSearchBarRoute
  TestOptionButtonRoute: typeof TestOptionButtonRoute
  TestToastRoute: typeof TestToastRoute
  TestTooltipRoute: typeof TestTooltipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching/': {
      id: '/matching/'
      path: '/'
      fullPath: '/matching/'
      preLoaderRoute: typeof MatchingIndexRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/test/tooltip': {
      id: '/test/tooltip'
      path: '/test/tooltip'
      fullPath: '/test/tooltip'
      preLoaderRoute: typeof TestTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/toast': {
      id: '/test/toast'
      path: '/test/toast'
      fullPath: '/test/toast'
      preLoaderRoute: typeof TestToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/option-button': {
      id: '/test/option-button'
      path: '/test/option-button'
      fullPath: '/test/option-button'
      preLoaderRoute: typeof TestOptionButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/member-search-bar': {
      id: '/test/member-search-bar'
      path: '/test/member-search-bar'
      fullPath: '/test/member-search-bar'
      preLoaderRoute: typeof TestMemberSearchBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/counter': {
      id: '/test/counter'
      path: '/test/counter'
      fullPath: '/test/counter'
      preLoaderRoute: typeof TestCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/chip': {
      id: '/test/chip'
      path: '/test/chip'
      fullPath: '/test/chip'
      preLoaderRoute: typeof TestChipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/button': {
      id: '/test/button'
      path: '/test/button'
      fullPath: '/test/button'
      preLoaderRoute: typeof TestButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching/rounds': {
      id: '/matching/rounds'
      path: '/rounds'
      fullPath: '/matching/rounds'
      preLoaderRoute: typeof MatchingRoundsRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/matching/applications': {
      id: '/matching/applications'
      path: '/applications'
      fullPath: '/matching/applications'
      preLoaderRoute: typeof MatchingApplicationsRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/matching/projects/': {
      id: '/matching/projects/'
      path: '/projects'
      fullPath: '/matching/projects/'
      preLoaderRoute: typeof MatchingProjectsIndexRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/matching/projects/new': {
      id: '/matching/projects/new'
      path: '/projects/new'
      fullPath: '/matching/projects/new'
      preLoaderRoute: typeof MatchingProjectsNewRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/matching/projects/announce': {
      id: '/matching/projects/announce'
      path: '/projects/announce'
      fullPath: '/matching/projects/announce'
      preLoaderRoute: typeof MatchingProjectsAnnounceRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
  }
}

interface MatchingRouteRouteChildren {
  MatchingApplicationsRoute: typeof MatchingApplicationsRoute
  MatchingRoundsRoute: typeof MatchingRoundsRoute
  MatchingIndexRoute: typeof MatchingIndexRoute
  MatchingProjectsAnnounceRoute: typeof MatchingProjectsAnnounceRoute
  MatchingProjectsNewRoute: typeof MatchingProjectsNewRoute
  MatchingProjectsIndexRoute: typeof MatchingProjectsIndexRoute
}

const MatchingRouteRouteChildren: MatchingRouteRouteChildren = {
  MatchingApplicationsRoute: MatchingApplicationsRoute,
  MatchingRoundsRoute: MatchingRoundsRoute,
  MatchingIndexRoute: MatchingIndexRoute,
  MatchingProjectsAnnounceRoute: MatchingProjectsAnnounceRoute,
  MatchingProjectsNewRoute: MatchingProjectsNewRoute,
  MatchingProjectsIndexRoute: MatchingProjectsIndexRoute,
}

const MatchingRouteRouteWithChildren = MatchingRouteRoute._addFileChildren(
  MatchingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRoute,
  MatchingRouteRoute: MatchingRouteRouteWithChildren,
  TestButtonRoute: TestButtonRoute,
  TestChipRoute: TestChipRoute,
  TestCounterRoute: TestCounterRoute,
  TestMemberSearchBarRoute: TestMemberSearchBarRoute,
  TestOptionButtonRoute: TestOptionButtonRoute,
  TestToastRoute: TestToastRoute,
  TestTooltipRoute: TestTooltipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
