/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChallengerVerificationRouteImport } from './routes/challenger-verification'
import { Route as AuthTestRouteImport } from './routes/auth-test'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as MatchingRouteRouteImport } from './routes/matching/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MatchingIndexRouteImport } from './routes/matching/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TestUsabilitySurveyRouteImport } from './routes/test/usability-survey'
import { Route as TestTooltipRouteImport } from './routes/test/tooltip'
import { Route as TestToggleInputsRouteImport } from './routes/test/toggle-inputs'
import { Route as TestToggleRouteImport } from './routes/test/toggle'
import { Route as TestToastRouteImport } from './routes/test/toast'
import { Route as TestSocialButtonRouteImport } from './routes/test/social-button'
import { Route as TestRatingFaceRouteImport } from './routes/test/rating-face'
import { Route as TestQuestionFormRouteImport } from './routes/test/question-form'
import { Route as TestOptionButtonRouteImport } from './routes/test/option-button'
import { Route as TestInputBoxRouteImport } from './routes/test/input-box'
import { Route as TestIconRouteImport } from './routes/test/icon'
import { Route as TestFormHeaderRouteImport } from './routes/test/form-header'
import { Route as TestFooterRouteImport } from './routes/test/footer'
import { Route as TestFloatingActionButtonRouteImport } from './routes/test/floating-action-button'
import { Route as TestFieldTypeButtonRouteImport } from './routes/test/field-type-button'
import { Route as TestCounterLabelRouteImport } from './routes/test/counter-label'
import { Route as TestCounterRouteImport } from './routes/test/counter'
import { Route as TestCodeInputRouteImport } from './routes/test/code-input'
import { Route as TestChipRouteImport } from './routes/test/chip'
import { Route as TestCheckboxRouteImport } from './routes/test/checkbox'
import { Route as TestChallengerVerificationRouteImport } from './routes/test/challenger-verification'
import { Route as TestButtonRouteImport } from './routes/test/button'
import { Route as TestApplicationFormRouteImport } from './routes/test/application-form'
import { Route as SignupOauthRouteImport } from './routes/signup/oauth'
import { Route as MatchingStatusRouteImport } from './routes/matching/status'
import { Route as MatchingRoundsRouteImport } from './routes/matching/rounds'
import { Route as MatchingNoticePublishRouteImport } from './routes/matching/notice-publish'
import { Route as MatchingApplicationsRouteImport } from './routes/matching/applications'
import { Route as LoginDefaultRouteImport } from './routes/login/default'
import { Route as MatchingProjectsIndexRouteImport } from './routes/matching/projects/index'
import { Route as OauthKakaoCallbackRouteImport } from './routes/oauth/kakao/callback'
import { Route as MatchingProjectsNewRouteImport } from './routes/matching/projects/new'
import { Route as MatchingProjectsManagementRouteImport } from './routes/matching/projects/management'
import { Route as MatchingNoticePublishNoticeIdRouteImport } from './routes/matching/notice-publish.$noticeId'
import { Route as AdminChallengerRecordsRouteImport } from './routes/admin/challenger/records'
import { Route as AdminChallengerPointsRouteImport } from './routes/admin/challenger/points'
import { Route as MatchingProjectsAnnounceRouteRouteImport } from './routes/matching/projects/announce/route'
import { Route as MatchingProjectsAnnounceIndexRouteImport } from './routes/matching/projects/announce/index'
import { Route as MatchingProjectsAnnounceNoticePublishRouteImport } from './routes/matching/projects/announce/notice-publish'
import { Route as MatchingProjectsAnnounceNoticePublishNoticeIdRouteImport } from './routes/matching/projects/announce/notice-publish.$noticeId'

const ChallengerVerificationRoute = ChallengerVerificationRouteImport.update({
  id: '/challenger-verification',
  path: '/challenger-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTestRoute = AuthTestRouteImport.update({
  id: '/auth-test',
  path: '/auth-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRouteRoute = MatchingRouteRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const MatchingIndexRoute = MatchingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TestUsabilitySurveyRoute = TestUsabilitySurveyRouteImport.update({
  id: '/test/usability-survey',
  path: '/test/usability-survey',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTooltipRoute = TestTooltipRouteImport.update({
  id: '/test/tooltip',
  path: '/test/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const TestToggleInputsRoute = TestToggleInputsRouteImport.update({
  id: '/test/toggle-inputs',
  path: '/test/toggle-inputs',
  getParentRoute: () => rootRouteImport,
} as any)
const TestToggleRoute = TestToggleRouteImport.update({
  id: '/test/toggle',
  path: '/test/toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const TestToastRoute = TestToastRouteImport.update({
  id: '/test/toast',
  path: '/test/toast',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSocialButtonRoute = TestSocialButtonRouteImport.update({
  id: '/test/social-button',
  path: '/test/social-button',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRatingFaceRoute = TestRatingFaceRouteImport.update({
  id: '/test/rating-face',
  path: '/test/rating-face',
  getParentRoute: () => rootRouteImport,
} as any)
const TestQuestionFormRoute = TestQuestionFormRouteImport.update({
  id: '/test/question-form',
  path: '/test/question-form',
  getParentRoute: () => rootRouteImport,
} as any)
const TestOptionButtonRoute = TestOptionButtonRouteImport.update({
  id: '/test/option-button',
  path: '/test/option-button',
  getParentRoute: () => rootRouteImport,
} as any)
const TestInputBoxRoute = TestInputBoxRouteImport.update({
  id: '/test/input-box',
  path: '/test/input-box',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIconRoute = TestIconRouteImport.update({
  id: '/test/icon',
  path: '/test/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFormHeaderRoute = TestFormHeaderRouteImport.update({
  id: '/test/form-header',
  path: '/test/form-header',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFooterRoute = TestFooterRouteImport.update({
  id: '/test/footer',
  path: '/test/footer',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFloatingActionButtonRoute =
  TestFloatingActionButtonRouteImport.update({
    id: '/test/floating-action-button',
    path: '/test/floating-action-button',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestFieldTypeButtonRoute = TestFieldTypeButtonRouteImport.update({
  id: '/test/field-type-button',
  path: '/test/field-type-button',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCounterLabelRoute = TestCounterLabelRouteImport.update({
  id: '/test/counter-label',
  path: '/test/counter-label',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCounterRoute = TestCounterRouteImport.update({
  id: '/test/counter',
  path: '/test/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCodeInputRoute = TestCodeInputRouteImport.update({
  id: '/test/code-input',
  path: '/test/code-input',
  getParentRoute: () => rootRouteImport,
} as any)
const TestChipRoute = TestChipRouteImport.update({
  id: '/test/chip',
  path: '/test/chip',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCheckboxRoute = TestCheckboxRouteImport.update({
  id: '/test/checkbox',
  path: '/test/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const TestChallengerVerificationRoute =
  TestChallengerVerificationRouteImport.update({
    id: '/test/challenger-verification',
    path: '/test/challenger-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestButtonRoute = TestButtonRouteImport.update({
  id: '/test/button',
  path: '/test/button',
  getParentRoute: () => rootRouteImport,
} as any)
const TestApplicationFormRoute = TestApplicationFormRouteImport.update({
  id: '/test/application-form',
  path: '/test/application-form',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupOauthRoute = SignupOauthRouteImport.update({
  id: '/signup/oauth',
  path: '/signup/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingStatusRoute = MatchingStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const MatchingRoundsRoute = MatchingRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const MatchingNoticePublishRoute = MatchingNoticePublishRouteImport.update({
  id: '/notice-publish',
  path: '/notice-publish',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const MatchingApplicationsRoute = MatchingApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const LoginDefaultRoute = LoginDefaultRouteImport.update({
  id: '/login/default',
  path: '/login/default',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingProjectsIndexRoute = MatchingProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const OauthKakaoCallbackRoute = OauthKakaoCallbackRouteImport.update({
  id: '/oauth/kakao/callback',
  path: '/oauth/kakao/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingProjectsNewRoute = MatchingProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => MatchingRouteRoute,
} as any)
const MatchingProjectsManagementRoute =
  MatchingProjectsManagementRouteImport.update({
    id: '/projects/management',
    path: '/projects/management',
    getParentRoute: () => MatchingRouteRoute,
  } as any)
const MatchingNoticePublishNoticeIdRoute =
  MatchingNoticePublishNoticeIdRouteImport.update({
    id: '/$noticeId',
    path: '/$noticeId',
    getParentRoute: () => MatchingNoticePublishRoute,
  } as any)
const AdminChallengerRecordsRoute = AdminChallengerRecordsRouteImport.update({
  id: '/challenger/records',
  path: '/challenger/records',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChallengerPointsRoute = AdminChallengerPointsRouteImport.update({
  id: '/challenger/points',
  path: '/challenger/points',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MatchingProjectsAnnounceRouteRoute =
  MatchingProjectsAnnounceRouteRouteImport.update({
    id: '/projects/announce',
    path: '/projects/announce',
    getParentRoute: () => MatchingRouteRoute,
  } as any)
const MatchingProjectsAnnounceIndexRoute =
  MatchingProjectsAnnounceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MatchingProjectsAnnounceRouteRoute,
  } as any)
const MatchingProjectsAnnounceNoticePublishRoute =
  MatchingProjectsAnnounceNoticePublishRouteImport.update({
    id: '/notice-publish',
    path: '/notice-publish',
    getParentRoute: () => MatchingProjectsAnnounceRouteRoute,
  } as any)
const MatchingProjectsAnnounceNoticePublishNoticeIdRoute =
  MatchingProjectsAnnounceNoticePublishNoticeIdRouteImport.update({
    id: '/$noticeId',
    path: '/$noticeId',
    getParentRoute: () => MatchingProjectsAnnounceNoticePublishRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/matching': typeof MatchingRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/auth-test': typeof AuthTestRoute
  '/challenger-verification': typeof ChallengerVerificationRoute
  '/login/default': typeof LoginDefaultRoute
  '/matching/applications': typeof MatchingApplicationsRoute
  '/matching/notice-publish': typeof MatchingNoticePublishRouteWithChildren
  '/matching/rounds': typeof MatchingRoundsRoute
  '/matching/status': typeof MatchingStatusRoute
  '/signup/oauth': typeof SignupOauthRoute
  '/test/application-form': typeof TestApplicationFormRoute
  '/test/button': typeof TestButtonRoute
  '/test/challenger-verification': typeof TestChallengerVerificationRoute
  '/test/checkbox': typeof TestCheckboxRoute
  '/test/chip': typeof TestChipRoute
  '/test/code-input': typeof TestCodeInputRoute
  '/test/counter': typeof TestCounterRoute
  '/test/counter-label': typeof TestCounterLabelRoute
  '/test/field-type-button': typeof TestFieldTypeButtonRoute
  '/test/floating-action-button': typeof TestFloatingActionButtonRoute
  '/test/footer': typeof TestFooterRoute
  '/test/form-header': typeof TestFormHeaderRoute
  '/test/icon': typeof TestIconRoute
  '/test/input-box': typeof TestInputBoxRoute
  '/test/option-button': typeof TestOptionButtonRoute
  '/test/question-form': typeof TestQuestionFormRoute
  '/test/rating-face': typeof TestRatingFaceRoute
  '/test/social-button': typeof TestSocialButtonRoute
  '/test/toast': typeof TestToastRoute
  '/test/toggle': typeof TestToggleRoute
  '/test/toggle-inputs': typeof TestToggleInputsRoute
  '/test/tooltip': typeof TestTooltipRoute
  '/test/usability-survey': typeof TestUsabilitySurveyRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/matching/': typeof MatchingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/test/': typeof TestIndexRoute
  '/matching/projects/announce': typeof MatchingProjectsAnnounceRouteRouteWithChildren
  '/admin/challenger/points': typeof AdminChallengerPointsRoute
  '/admin/challenger/records': typeof AdminChallengerRecordsRoute
  '/matching/notice-publish/$noticeId': typeof MatchingNoticePublishNoticeIdRoute
  '/matching/projects/management': typeof MatchingProjectsManagementRoute
  '/matching/projects/new': typeof MatchingProjectsNewRoute
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/matching/projects/': typeof MatchingProjectsIndexRoute
  '/matching/projects/announce/notice-publish': typeof MatchingProjectsAnnounceNoticePublishRouteWithChildren
  '/matching/projects/announce/': typeof MatchingProjectsAnnounceIndexRoute
  '/matching/projects/announce/notice-publish/$noticeId': typeof MatchingProjectsAnnounceNoticePublishNoticeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-test': typeof AuthTestRoute
  '/challenger-verification': typeof ChallengerVerificationRoute
  '/login/default': typeof LoginDefaultRoute
  '/matching/applications': typeof MatchingApplicationsRoute
  '/matching/notice-publish': typeof MatchingNoticePublishRouteWithChildren
  '/matching/rounds': typeof MatchingRoundsRoute
  '/matching/status': typeof MatchingStatusRoute
  '/signup/oauth': typeof SignupOauthRoute
  '/test/application-form': typeof TestApplicationFormRoute
  '/test/button': typeof TestButtonRoute
  '/test/challenger-verification': typeof TestChallengerVerificationRoute
  '/test/checkbox': typeof TestCheckboxRoute
  '/test/chip': typeof TestChipRoute
  '/test/code-input': typeof TestCodeInputRoute
  '/test/counter': typeof TestCounterRoute
  '/test/counter-label': typeof TestCounterLabelRoute
  '/test/field-type-button': typeof TestFieldTypeButtonRoute
  '/test/floating-action-button': typeof TestFloatingActionButtonRoute
  '/test/footer': typeof TestFooterRoute
  '/test/form-header': typeof TestFormHeaderRoute
  '/test/icon': typeof TestIconRoute
  '/test/input-box': typeof TestInputBoxRoute
  '/test/option-button': typeof TestOptionButtonRoute
  '/test/question-form': typeof TestQuestionFormRoute
  '/test/rating-face': typeof TestRatingFaceRoute
  '/test/social-button': typeof TestSocialButtonRoute
  '/test/toast': typeof TestToastRoute
  '/test/toggle': typeof TestToggleRoute
  '/test/toggle-inputs': typeof TestToggleInputsRoute
  '/test/tooltip': typeof TestTooltipRoute
  '/test/usability-survey': typeof TestUsabilitySurveyRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/matching': typeof MatchingIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/signup': typeof SignupIndexRoute
  '/test': typeof TestIndexRoute
  '/admin/challenger/points': typeof AdminChallengerPointsRoute
  '/admin/challenger/records': typeof AdminChallengerRecordsRoute
  '/matching/notice-publish/$noticeId': typeof MatchingNoticePublishNoticeIdRoute
  '/matching/projects/management': typeof MatchingProjectsManagementRoute
  '/matching/projects/new': typeof MatchingProjectsNewRoute
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/matching/projects': typeof MatchingProjectsIndexRoute
  '/matching/projects/announce/notice-publish': typeof MatchingProjectsAnnounceNoticePublishRouteWithChildren
  '/matching/projects/announce': typeof MatchingProjectsAnnounceIndexRoute
  '/matching/projects/announce/notice-publish/$noticeId': typeof MatchingProjectsAnnounceNoticePublishNoticeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/matching': typeof MatchingRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/auth-test': typeof AuthTestRoute
  '/challenger-verification': typeof ChallengerVerificationRoute
  '/login/default': typeof LoginDefaultRoute
  '/matching/applications': typeof MatchingApplicationsRoute
  '/matching/notice-publish': typeof MatchingNoticePublishRouteWithChildren
  '/matching/rounds': typeof MatchingRoundsRoute
  '/matching/status': typeof MatchingStatusRoute
  '/signup/oauth': typeof SignupOauthRoute
  '/test/application-form': typeof TestApplicationFormRoute
  '/test/button': typeof TestButtonRoute
  '/test/challenger-verification': typeof TestChallengerVerificationRoute
  '/test/checkbox': typeof TestCheckboxRoute
  '/test/chip': typeof TestChipRoute
  '/test/code-input': typeof TestCodeInputRoute
  '/test/counter': typeof TestCounterRoute
  '/test/counter-label': typeof TestCounterLabelRoute
  '/test/field-type-button': typeof TestFieldTypeButtonRoute
  '/test/floating-action-button': typeof TestFloatingActionButtonRoute
  '/test/footer': typeof TestFooterRoute
  '/test/form-header': typeof TestFormHeaderRoute
  '/test/icon': typeof TestIconRoute
  '/test/input-box': typeof TestInputBoxRoute
  '/test/option-button': typeof TestOptionButtonRoute
  '/test/question-form': typeof TestQuestionFormRoute
  '/test/rating-face': typeof TestRatingFaceRoute
  '/test/social-button': typeof TestSocialButtonRoute
  '/test/toast': typeof TestToastRoute
  '/test/toggle': typeof TestToggleRoute
  '/test/toggle-inputs': typeof TestToggleInputsRoute
  '/test/tooltip': typeof TestTooltipRoute
  '/test/usability-survey': typeof TestUsabilitySurveyRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/matching/': typeof MatchingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/test/': typeof TestIndexRoute
  '/matching/projects/announce': typeof MatchingProjectsAnnounceRouteRouteWithChildren
  '/admin/challenger/points': typeof AdminChallengerPointsRoute
  '/admin/challenger/records': typeof AdminChallengerRecordsRoute
  '/matching/notice-publish/$noticeId': typeof MatchingNoticePublishNoticeIdRoute
  '/matching/projects/management': typeof MatchingProjectsManagementRoute
  '/matching/projects/new': typeof MatchingProjectsNewRoute
  '/oauth/kakao/callback': typeof OauthKakaoCallbackRoute
  '/matching/projects/': typeof MatchingProjectsIndexRoute
  '/matching/projects/announce/notice-publish': typeof MatchingProjectsAnnounceNoticePublishRouteWithChildren
  '/matching/projects/announce/': typeof MatchingProjectsAnnounceIndexRoute
  '/matching/projects/announce/notice-publish/$noticeId': typeof MatchingProjectsAnnounceNoticePublishNoticeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/matching'
    | '/settings'
    | '/auth-test'
    | '/challenger-verification'
    | '/login/default'
    | '/matching/applications'
    | '/matching/notice-publish'
    | '/matching/rounds'
    | '/matching/status'
    | '/signup/oauth'
    | '/test/application-form'
    | '/test/button'
    | '/test/challenger-verification'
    | '/test/checkbox'
    | '/test/chip'
    | '/test/code-input'
    | '/test/counter'
    | '/test/counter-label'
    | '/test/field-type-button'
    | '/test/floating-action-button'
    | '/test/footer'
    | '/test/form-header'
    | '/test/icon'
    | '/test/input-box'
    | '/test/option-button'
    | '/test/question-form'
    | '/test/rating-face'
    | '/test/social-button'
    | '/test/toast'
    | '/test/toggle'
    | '/test/toggle-inputs'
    | '/test/tooltip'
    | '/test/usability-survey'
    | '/admin/'
    | '/login/'
    | '/matching/'
    | '/settings/'
    | '/signup/'
    | '/test/'
    | '/matching/projects/announce'
    | '/admin/challenger/points'
    | '/admin/challenger/records'
    | '/matching/notice-publish/$noticeId'
    | '/matching/projects/management'
    | '/matching/projects/new'
    | '/oauth/kakao/callback'
    | '/matching/projects/'
    | '/matching/projects/announce/notice-publish'
    | '/matching/projects/announce/'
    | '/matching/projects/announce/notice-publish/$noticeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-test'
    | '/challenger-verification'
    | '/login/default'
    | '/matching/applications'
    | '/matching/notice-publish'
    | '/matching/rounds'
    | '/matching/status'
    | '/signup/oauth'
    | '/test/application-form'
    | '/test/button'
    | '/test/challenger-verification'
    | '/test/checkbox'
    | '/test/chip'
    | '/test/code-input'
    | '/test/counter'
    | '/test/counter-label'
    | '/test/field-type-button'
    | '/test/floating-action-button'
    | '/test/footer'
    | '/test/form-header'
    | '/test/icon'
    | '/test/input-box'
    | '/test/option-button'
    | '/test/question-form'
    | '/test/rating-face'
    | '/test/social-button'
    | '/test/toast'
    | '/test/toggle'
    | '/test/toggle-inputs'
    | '/test/tooltip'
    | '/test/usability-survey'
    | '/admin'
    | '/login'
    | '/matching'
    | '/settings'
    | '/signup'
    | '/test'
    | '/admin/challenger/points'
    | '/admin/challenger/records'
    | '/matching/notice-publish/$noticeId'
    | '/matching/projects/management'
    | '/matching/projects/new'
    | '/oauth/kakao/callback'
    | '/matching/projects'
    | '/matching/projects/announce/notice-publish'
    | '/matching/projects/announce'
    | '/matching/projects/announce/notice-publish/$noticeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/matching'
    | '/settings'
    | '/auth-test'
    | '/challenger-verification'
    | '/login/default'
    | '/matching/applications'
    | '/matching/notice-publish'
    | '/matching/rounds'
    | '/matching/status'
    | '/signup/oauth'
    | '/test/application-form'
    | '/test/button'
    | '/test/challenger-verification'
    | '/test/checkbox'
    | '/test/chip'
    | '/test/code-input'
    | '/test/counter'
    | '/test/counter-label'
    | '/test/field-type-button'
    | '/test/floating-action-button'
    | '/test/footer'
    | '/test/form-header'
    | '/test/icon'
    | '/test/input-box'
    | '/test/option-button'
    | '/test/question-form'
    | '/test/rating-face'
    | '/test/social-button'
    | '/test/toast'
    | '/test/toggle'
    | '/test/toggle-inputs'
    | '/test/tooltip'
    | '/test/usability-survey'
    | '/admin/'
    | '/login/'
    | '/matching/'
    | '/settings/'
    | '/signup/'
    | '/test/'
    | '/matching/projects/announce'
    | '/admin/challenger/points'
    | '/admin/challenger/records'
    | '/matching/notice-publish/$noticeId'
    | '/matching/projects/management'
    | '/matching/projects/new'
    | '/oauth/kakao/callback'
    | '/matching/projects/'
    | '/matching/projects/announce/notice-publish'
    | '/matching/projects/announce/'
    | '/matching/projects/announce/notice-publish/$noticeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MatchingRouteRoute: typeof MatchingRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AuthTestRoute: typeof AuthTestRoute
  ChallengerVerificationRoute: typeof ChallengerVerificationRoute
  LoginDefaultRoute: typeof LoginDefaultRoute
  SignupOauthRoute: typeof SignupOauthRoute
  TestApplicationFormRoute: typeof TestApplicationFormRoute
  TestButtonRoute: typeof TestButtonRoute
  TestChallengerVerificationRoute: typeof TestChallengerVerificationRoute
  TestCheckboxRoute: typeof TestCheckboxRoute
  TestChipRoute: typeof TestChipRoute
  TestCodeInputRoute: typeof TestCodeInputRoute
  TestCounterRoute: typeof TestCounterRoute
  TestCounterLabelRoute: typeof TestCounterLabelRoute
  TestFieldTypeButtonRoute: typeof TestFieldTypeButtonRoute
  TestFloatingActionButtonRoute: typeof TestFloatingActionButtonRoute
  TestFooterRoute: typeof TestFooterRoute
  TestFormHeaderRoute: typeof TestFormHeaderRoute
  TestIconRoute: typeof TestIconRoute
  TestInputBoxRoute: typeof TestInputBoxRoute
  TestOptionButtonRoute: typeof TestOptionButtonRoute
  TestQuestionFormRoute: typeof TestQuestionFormRoute
  TestRatingFaceRoute: typeof TestRatingFaceRoute
  TestSocialButtonRoute: typeof TestSocialButtonRoute
  TestToastRoute: typeof TestToastRoute
  TestToggleRoute: typeof TestToggleRoute
  TestToggleInputsRoute: typeof TestToggleInputsRoute
  TestTooltipRoute: typeof TestTooltipRoute
  TestUsabilitySurveyRoute: typeof TestUsabilitySurveyRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  OauthKakaoCallbackRoute: typeof OauthKakaoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/challenger-verification': {
      id: '/challenger-verification'
      path: '/challenger-verification'
      fullPath: '/challenger-verification'
      preLoaderRoute: typeof ChallengerVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-test': {
      id: '/auth-test'
      path: '/auth-test'
      fullPath: '/auth-test'
      preLoaderRoute: typeof AuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/matching/': {
      id: '/matching/'
      path: '/'
      fullPath: '/matching/'
      preLoaderRoute: typeof MatchingIndexRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/test/usability-survey': {
      id: '/test/usability-survey'
      path: '/test/usability-survey'
      fullPath: '/test/usability-survey'
      preLoaderRoute: typeof TestUsabilitySurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/tooltip': {
      id: '/test/tooltip'
      path: '/test/tooltip'
      fullPath: '/test/tooltip'
      preLoaderRoute: typeof TestTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/toggle-inputs': {
      id: '/test/toggle-inputs'
      path: '/test/toggle-inputs'
      fullPath: '/test/toggle-inputs'
      preLoaderRoute: typeof TestToggleInputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/toggle': {
      id: '/test/toggle'
      path: '/test/toggle'
      fullPath: '/test/toggle'
      preLoaderRoute: typeof TestToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/toast': {
      id: '/test/toast'
      path: '/test/toast'
      fullPath: '/test/toast'
      preLoaderRoute: typeof TestToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/social-button': {
      id: '/test/social-button'
      path: '/test/social-button'
      fullPath: '/test/social-button'
      preLoaderRoute: typeof TestSocialButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/rating-face': {
      id: '/test/rating-face'
      path: '/test/rating-face'
      fullPath: '/test/rating-face'
      preLoaderRoute: typeof TestRatingFaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/question-form': {
      id: '/test/question-form'
      path: '/test/question-form'
      fullPath: '/test/question-form'
      preLoaderRoute: typeof TestQuestionFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/option-button': {
      id: '/test/option-button'
      path: '/test/option-button'
      fullPath: '/test/option-button'
      preLoaderRoute: typeof TestOptionButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/input-box': {
      id: '/test/input-box'
      path: '/test/input-box'
      fullPath: '/test/input-box'
      preLoaderRoute: typeof TestInputBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/icon': {
      id: '/test/icon'
      path: '/test/icon'
      fullPath: '/test/icon'
      preLoaderRoute: typeof TestIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/form-header': {
      id: '/test/form-header'
      path: '/test/form-header'
      fullPath: '/test/form-header'
      preLoaderRoute: typeof TestFormHeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/footer': {
      id: '/test/footer'
      path: '/test/footer'
      fullPath: '/test/footer'
      preLoaderRoute: typeof TestFooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/floating-action-button': {
      id: '/test/floating-action-button'
      path: '/test/floating-action-button'
      fullPath: '/test/floating-action-button'
      preLoaderRoute: typeof TestFloatingActionButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/field-type-button': {
      id: '/test/field-type-button'
      path: '/test/field-type-button'
      fullPath: '/test/field-type-button'
      preLoaderRoute: typeof TestFieldTypeButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/counter-label': {
      id: '/test/counter-label'
      path: '/test/counter-label'
      fullPath: '/test/counter-label'
      preLoaderRoute: typeof TestCounterLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/counter': {
      id: '/test/counter'
      path: '/test/counter'
      fullPath: '/test/counter'
      preLoaderRoute: typeof TestCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/code-input': {
      id: '/test/code-input'
      path: '/test/code-input'
      fullPath: '/test/code-input'
      preLoaderRoute: typeof TestCodeInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/chip': {
      id: '/test/chip'
      path: '/test/chip'
      fullPath: '/test/chip'
      preLoaderRoute: typeof TestChipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/checkbox': {
      id: '/test/checkbox'
      path: '/test/checkbox'
      fullPath: '/test/checkbox'
      preLoaderRoute: typeof TestCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/challenger-verification': {
      id: '/test/challenger-verification'
      path: '/test/challenger-verification'
      fullPath: '/test/challenger-verification'
      preLoaderRoute: typeof TestChallengerVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/button': {
      id: '/test/button'
      path: '/test/button'
      fullPath: '/test/button'
      preLoaderRoute: typeof TestButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/application-form': {
      id: '/test/application-form'
      path: '/test/application-form'
      fullPath: '/test/application-form'
      preLoaderRoute: typeof TestApplicationFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/oauth': {
      id: '/signup/oauth'
      path: '/signup/oauth'
      fullPath: '/signup/oauth'
      preLoaderRoute: typeof SignupOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching/status': {
      id: '/matching/status'
      path: '/status'
      fullPath: '/matching/status'
      preLoaderRoute: typeof MatchingStatusRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/matching/rounds': {
      id: '/matching/rounds'
      path: '/rounds'
      fullPath: '/matching/rounds'
      preLoaderRoute: typeof MatchingRoundsRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/matching/notice-publish': {
      id: '/matching/notice-publish'
      path: '/notice-publish'
      fullPath: '/matching/notice-publish'
      preLoaderRoute: typeof MatchingNoticePublishRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/matching/applications': {
      id: '/matching/applications'
      path: '/applications'
      fullPath: '/matching/applications'
      preLoaderRoute: typeof MatchingApplicationsRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/login/default': {
      id: '/login/default'
      path: '/login/default'
      fullPath: '/login/default'
      preLoaderRoute: typeof LoginDefaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching/projects/': {
      id: '/matching/projects/'
      path: '/projects'
      fullPath: '/matching/projects/'
      preLoaderRoute: typeof MatchingProjectsIndexRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/oauth/kakao/callback': {
      id: '/oauth/kakao/callback'
      path: '/oauth/kakao/callback'
      fullPath: '/oauth/kakao/callback'
      preLoaderRoute: typeof OauthKakaoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching/projects/new': {
      id: '/matching/projects/new'
      path: '/projects/new'
      fullPath: '/matching/projects/new'
      preLoaderRoute: typeof MatchingProjectsNewRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/matching/projects/management': {
      id: '/matching/projects/management'
      path: '/projects/management'
      fullPath: '/matching/projects/management'
      preLoaderRoute: typeof MatchingProjectsManagementRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/matching/notice-publish/$noticeId': {
      id: '/matching/notice-publish/$noticeId'
      path: '/$noticeId'
      fullPath: '/matching/notice-publish/$noticeId'
      preLoaderRoute: typeof MatchingNoticePublishNoticeIdRouteImport
      parentRoute: typeof MatchingNoticePublishRoute
    }
    '/admin/challenger/records': {
      id: '/admin/challenger/records'
      path: '/challenger/records'
      fullPath: '/admin/challenger/records'
      preLoaderRoute: typeof AdminChallengerRecordsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/challenger/points': {
      id: '/admin/challenger/points'
      path: '/challenger/points'
      fullPath: '/admin/challenger/points'
      preLoaderRoute: typeof AdminChallengerPointsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/matching/projects/announce': {
      id: '/matching/projects/announce'
      path: '/projects/announce'
      fullPath: '/matching/projects/announce'
      preLoaderRoute: typeof MatchingProjectsAnnounceRouteRouteImport
      parentRoute: typeof MatchingRouteRoute
    }
    '/matching/projects/announce/': {
      id: '/matching/projects/announce/'
      path: '/'
      fullPath: '/matching/projects/announce/'
      preLoaderRoute: typeof MatchingProjectsAnnounceIndexRouteImport
      parentRoute: typeof MatchingProjectsAnnounceRouteRoute
    }
    '/matching/projects/announce/notice-publish': {
      id: '/matching/projects/announce/notice-publish'
      path: '/notice-publish'
      fullPath: '/matching/projects/announce/notice-publish'
      preLoaderRoute: typeof MatchingProjectsAnnounceNoticePublishRouteImport
      parentRoute: typeof MatchingProjectsAnnounceRouteRoute
    }
    '/matching/projects/announce/notice-publish/$noticeId': {
      id: '/matching/projects/announce/notice-publish/$noticeId'
      path: '/$noticeId'
      fullPath: '/matching/projects/announce/notice-publish/$noticeId'
      preLoaderRoute: typeof MatchingProjectsAnnounceNoticePublishNoticeIdRouteImport
      parentRoute: typeof MatchingProjectsAnnounceNoticePublishRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminChallengerPointsRoute: typeof AdminChallengerPointsRoute
  AdminChallengerRecordsRoute: typeof AdminChallengerRecordsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminChallengerPointsRoute: AdminChallengerPointsRoute,
  AdminChallengerRecordsRoute: AdminChallengerRecordsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MatchingNoticePublishRouteChildren {
  MatchingNoticePublishNoticeIdRoute: typeof MatchingNoticePublishNoticeIdRoute
}

const MatchingNoticePublishRouteChildren: MatchingNoticePublishRouteChildren = {
  MatchingNoticePublishNoticeIdRoute: MatchingNoticePublishNoticeIdRoute,
}

const MatchingNoticePublishRouteWithChildren =
  MatchingNoticePublishRoute._addFileChildren(
    MatchingNoticePublishRouteChildren,
  )

interface MatchingProjectsAnnounceNoticePublishRouteChildren {
  MatchingProjectsAnnounceNoticePublishNoticeIdRoute: typeof MatchingProjectsAnnounceNoticePublishNoticeIdRoute
}

const MatchingProjectsAnnounceNoticePublishRouteChildren: MatchingProjectsAnnounceNoticePublishRouteChildren =
  {
    MatchingProjectsAnnounceNoticePublishNoticeIdRoute:
      MatchingProjectsAnnounceNoticePublishNoticeIdRoute,
  }

const MatchingProjectsAnnounceNoticePublishRouteWithChildren =
  MatchingProjectsAnnounceNoticePublishRoute._addFileChildren(
    MatchingProjectsAnnounceNoticePublishRouteChildren,
  )

interface MatchingProjectsAnnounceRouteRouteChildren {
  MatchingProjectsAnnounceNoticePublishRoute: typeof MatchingProjectsAnnounceNoticePublishRouteWithChildren
  MatchingProjectsAnnounceIndexRoute: typeof MatchingProjectsAnnounceIndexRoute
}

const MatchingProjectsAnnounceRouteRouteChildren: MatchingProjectsAnnounceRouteRouteChildren =
  {
    MatchingProjectsAnnounceNoticePublishRoute:
      MatchingProjectsAnnounceNoticePublishRouteWithChildren,
    MatchingProjectsAnnounceIndexRoute: MatchingProjectsAnnounceIndexRoute,
  }

const MatchingProjectsAnnounceRouteRouteWithChildren =
  MatchingProjectsAnnounceRouteRoute._addFileChildren(
    MatchingProjectsAnnounceRouteRouteChildren,
  )

interface MatchingRouteRouteChildren {
  MatchingApplicationsRoute: typeof MatchingApplicationsRoute
  MatchingNoticePublishRoute: typeof MatchingNoticePublishRouteWithChildren
  MatchingRoundsRoute: typeof MatchingRoundsRoute
  MatchingStatusRoute: typeof MatchingStatusRoute
  MatchingIndexRoute: typeof MatchingIndexRoute
  MatchingProjectsAnnounceRouteRoute: typeof MatchingProjectsAnnounceRouteRouteWithChildren
  MatchingProjectsManagementRoute: typeof MatchingProjectsManagementRoute
  MatchingProjectsNewRoute: typeof MatchingProjectsNewRoute
  MatchingProjectsIndexRoute: typeof MatchingProjectsIndexRoute
}

const MatchingRouteRouteChildren: MatchingRouteRouteChildren = {
  MatchingApplicationsRoute: MatchingApplicationsRoute,
  MatchingNoticePublishRoute: MatchingNoticePublishRouteWithChildren,
  MatchingRoundsRoute: MatchingRoundsRoute,
  MatchingStatusRoute: MatchingStatusRoute,
  MatchingIndexRoute: MatchingIndexRoute,
  MatchingProjectsAnnounceRouteRoute:
    MatchingProjectsAnnounceRouteRouteWithChildren,
  MatchingProjectsManagementRoute: MatchingProjectsManagementRoute,
  MatchingProjectsNewRoute: MatchingProjectsNewRoute,
  MatchingProjectsIndexRoute: MatchingProjectsIndexRoute,
}

const MatchingRouteRouteWithChildren = MatchingRouteRoute._addFileChildren(
  MatchingRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MatchingRouteRoute: MatchingRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AuthTestRoute: AuthTestRoute,
  ChallengerVerificationRoute: ChallengerVerificationRoute,
  LoginDefaultRoute: LoginDefaultRoute,
  SignupOauthRoute: SignupOauthRoute,
  TestApplicationFormRoute: TestApplicationFormRoute,
  TestButtonRoute: TestButtonRoute,
  TestChallengerVerificationRoute: TestChallengerVerificationRoute,
  TestCheckboxRoute: TestCheckboxRoute,
  TestChipRoute: TestChipRoute,
  TestCodeInputRoute: TestCodeInputRoute,
  TestCounterRoute: TestCounterRoute,
  TestCounterLabelRoute: TestCounterLabelRoute,
  TestFieldTypeButtonRoute: TestFieldTypeButtonRoute,
  TestFloatingActionButtonRoute: TestFloatingActionButtonRoute,
  TestFooterRoute: TestFooterRoute,
  TestFormHeaderRoute: TestFormHeaderRoute,
  TestIconRoute: TestIconRoute,
  TestInputBoxRoute: TestInputBoxRoute,
  TestOptionButtonRoute: TestOptionButtonRoute,
  TestQuestionFormRoute: TestQuestionFormRoute,
  TestRatingFaceRoute: TestRatingFaceRoute,
  TestSocialButtonRoute: TestSocialButtonRoute,
  TestToastRoute: TestToastRoute,
  TestToggleRoute: TestToggleRoute,
  TestToggleInputsRoute: TestToggleInputsRoute,
  TestTooltipRoute: TestTooltipRoute,
  TestUsabilitySurveyRoute: TestUsabilitySurveyRoute,
  LoginIndexRoute: LoginIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  TestIndexRoute: TestIndexRoute,
  OauthKakaoCallbackRoute: OauthKakaoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
