/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestSidebarRouteImport } from './routes/test/sidebar'
import { Route as TestSidebarIndexRouteImport } from './routes/test/sidebar/index'
import { Route as TestSidebarProjectRegisterRouteImport } from './routes/test/sidebar/project-register'
import { Route as TestSidebarProjectNoticeRouteImport } from './routes/test/sidebar/project-notice'
import { Route as TestSidebarProjectListRouteImport } from './routes/test/sidebar/project-list'
import { Route as TestSidebarMatchingRoundRouteImport } from './routes/test/sidebar/matching-round'
import { Route as TestSidebarMatchingNoticeRouteImport } from './routes/test/sidebar/matching-notice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSidebarRoute = TestSidebarRouteImport.update({
  id: '/test/sidebar',
  path: '/test/sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSidebarIndexRoute = TestSidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestSidebarRoute,
} as any)
const TestSidebarProjectRegisterRoute =
  TestSidebarProjectRegisterRouteImport.update({
    id: '/project-register',
    path: '/project-register',
    getParentRoute: () => TestSidebarRoute,
  } as any)
const TestSidebarProjectNoticeRoute =
  TestSidebarProjectNoticeRouteImport.update({
    id: '/project-notice',
    path: '/project-notice',
    getParentRoute: () => TestSidebarRoute,
  } as any)
const TestSidebarProjectListRoute = TestSidebarProjectListRouteImport.update({
  id: '/project-list',
  path: '/project-list',
  getParentRoute: () => TestSidebarRoute,
} as any)
const TestSidebarMatchingRoundRoute =
  TestSidebarMatchingRoundRouteImport.update({
    id: '/matching-round',
    path: '/matching-round',
    getParentRoute: () => TestSidebarRoute,
  } as any)
const TestSidebarMatchingNoticeRoute =
  TestSidebarMatchingNoticeRouteImport.update({
    id: '/matching-notice',
    path: '/matching-notice',
    getParentRoute: () => TestSidebarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test/sidebar': typeof TestSidebarRouteWithChildren
  '/test/sidebar/matching-notice': typeof TestSidebarMatchingNoticeRoute
  '/test/sidebar/matching-round': typeof TestSidebarMatchingRoundRoute
  '/test/sidebar/project-list': typeof TestSidebarProjectListRoute
  '/test/sidebar/project-notice': typeof TestSidebarProjectNoticeRoute
  '/test/sidebar/project-register': typeof TestSidebarProjectRegisterRoute
  '/test/sidebar/': typeof TestSidebarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test/sidebar/matching-notice': typeof TestSidebarMatchingNoticeRoute
  '/test/sidebar/matching-round': typeof TestSidebarMatchingRoundRoute
  '/test/sidebar/project-list': typeof TestSidebarProjectListRoute
  '/test/sidebar/project-notice': typeof TestSidebarProjectNoticeRoute
  '/test/sidebar/project-register': typeof TestSidebarProjectRegisterRoute
  '/test/sidebar': typeof TestSidebarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test/sidebar': typeof TestSidebarRouteWithChildren
  '/test/sidebar/matching-notice': typeof TestSidebarMatchingNoticeRoute
  '/test/sidebar/matching-round': typeof TestSidebarMatchingRoundRoute
  '/test/sidebar/project-list': typeof TestSidebarProjectListRoute
  '/test/sidebar/project-notice': typeof TestSidebarProjectNoticeRoute
  '/test/sidebar/project-register': typeof TestSidebarProjectRegisterRoute
  '/test/sidebar/': typeof TestSidebarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test/sidebar'
    | '/test/sidebar/matching-notice'
    | '/test/sidebar/matching-round'
    | '/test/sidebar/project-list'
    | '/test/sidebar/project-notice'
    | '/test/sidebar/project-register'
    | '/test/sidebar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test/sidebar/matching-notice'
    | '/test/sidebar/matching-round'
    | '/test/sidebar/project-list'
    | '/test/sidebar/project-notice'
    | '/test/sidebar/project-register'
    | '/test/sidebar'
  id:
    | '__root__'
    | '/'
    | '/test/sidebar'
    | '/test/sidebar/matching-notice'
    | '/test/sidebar/matching-round'
    | '/test/sidebar/project-list'
    | '/test/sidebar/project-notice'
    | '/test/sidebar/project-register'
    | '/test/sidebar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestSidebarRoute: typeof TestSidebarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/sidebar': {
      id: '/test/sidebar'
      path: '/test/sidebar'
      fullPath: '/test/sidebar'
      preLoaderRoute: typeof TestSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/sidebar/': {
      id: '/test/sidebar/'
      path: '/'
      fullPath: '/test/sidebar/'
      preLoaderRoute: typeof TestSidebarIndexRouteImport
      parentRoute: typeof TestSidebarRoute
    }
    '/test/sidebar/project-register': {
      id: '/test/sidebar/project-register'
      path: '/project-register'
      fullPath: '/test/sidebar/project-register'
      preLoaderRoute: typeof TestSidebarProjectRegisterRouteImport
      parentRoute: typeof TestSidebarRoute
    }
    '/test/sidebar/project-notice': {
      id: '/test/sidebar/project-notice'
      path: '/project-notice'
      fullPath: '/test/sidebar/project-notice'
      preLoaderRoute: typeof TestSidebarProjectNoticeRouteImport
      parentRoute: typeof TestSidebarRoute
    }
    '/test/sidebar/project-list': {
      id: '/test/sidebar/project-list'
      path: '/project-list'
      fullPath: '/test/sidebar/project-list'
      preLoaderRoute: typeof TestSidebarProjectListRouteImport
      parentRoute: typeof TestSidebarRoute
    }
    '/test/sidebar/matching-round': {
      id: '/test/sidebar/matching-round'
      path: '/matching-round'
      fullPath: '/test/sidebar/matching-round'
      preLoaderRoute: typeof TestSidebarMatchingRoundRouteImport
      parentRoute: typeof TestSidebarRoute
    }
    '/test/sidebar/matching-notice': {
      id: '/test/sidebar/matching-notice'
      path: '/matching-notice'
      fullPath: '/test/sidebar/matching-notice'
      preLoaderRoute: typeof TestSidebarMatchingNoticeRouteImport
      parentRoute: typeof TestSidebarRoute
    }
  }
}

interface TestSidebarRouteChildren {
  TestSidebarMatchingNoticeRoute: typeof TestSidebarMatchingNoticeRoute
  TestSidebarMatchingRoundRoute: typeof TestSidebarMatchingRoundRoute
  TestSidebarProjectListRoute: typeof TestSidebarProjectListRoute
  TestSidebarProjectNoticeRoute: typeof TestSidebarProjectNoticeRoute
  TestSidebarProjectRegisterRoute: typeof TestSidebarProjectRegisterRoute
  TestSidebarIndexRoute: typeof TestSidebarIndexRoute
}

const TestSidebarRouteChildren: TestSidebarRouteChildren = {
  TestSidebarMatchingNoticeRoute: TestSidebarMatchingNoticeRoute,
  TestSidebarMatchingRoundRoute: TestSidebarMatchingRoundRoute,
  TestSidebarProjectListRoute: TestSidebarProjectListRoute,
  TestSidebarProjectNoticeRoute: TestSidebarProjectNoticeRoute,
  TestSidebarProjectRegisterRoute: TestSidebarProjectRegisterRoute,
  TestSidebarIndexRoute: TestSidebarIndexRoute,
}

const TestSidebarRouteWithChildren = TestSidebarRoute._addFileChildren(
  TestSidebarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestSidebarRoute: TestSidebarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
